const A={hero:'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=2400&q=90',people:'https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1800&q=90',stage:'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1800&q=90',register:'https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=2200&q=90'};
const TOT_LOGO='tot_logo_bg.png';
const load=s=>new Promise((ok,no)=>{const x=document.createElement('script');x.src=s;x.onload=ok;x.onerror=no;document.head.appendChild(x)});
const app=document.querySelector('#app');
app.innerHTML=`
<div class="loader" id="loader"><div><img src="${TOT_LOGO}" alt="Triumphs of Talent"><strong>PRESENTS</strong><h2>INDIA <i>INCLUSIVE</i><br>SUMMIT</h2><span></span></div></div>
<div class="cursor"></div><div class="progress"></div>
<header><a class="logo" href="#home" aria-label="Triumphs of Talent — India Inclusive Summit"><img src="${TOT_LOGO}" alt="Triumphs of Talent"><span class="presents">PRESENTS</span><b>INDIA INCLUSIVE SUMMIT</b></a><button class="menu" aria-label="Open menu">☰</button><nav><a href="#home">Home</a><a href="#why">Why the Summit</a><a href="#register" class="cta">Register your interest</a></nav></header>
<main>
<section class="home" id="home"><img src="${A.hero}" alt="People collaborating at a professional summit"><div class="shade"></div><div class="home-copy"><small>TRIUMPHS OF TALENT PRESENTS</small><h1>India <em>Inclusive</em><br>Summit.</h1><p>Breaking barriers. Building pathways. A national platform bringing lived experience, business leadership, policy and innovation together to create a more inclusive India.</p><div class="actions"><a class="btn primary" href="#register">Register your interest <span>↗</span></a><a class="btn" href="#why">Discover the summit <span>↓</span></a></div></div><div class="home-bottom"><span>INCLUSION / ACCESS / OPPORTUNITY</span><span>SCROLL TO EXPLORE ↓</span></div></section>
<section class="why" id="why"><div class="why-intro reveal"><div><small>02 / WHY THE SUMMIT</small><h2>Inclusion is not<br>a conversation.<br><em>It is action.</em></h2></div><p>India has extraordinary talent. Yet opportunity is still shaped by barriers in access, employment, technology and everyday participation. India Inclusive Summit brings the people who experience those barriers together with the people who can remove them.</p></div><div class="why-track"><article><b>01</b><small>THE PURPOSE</small><h3>Move beyond awareness.</h3><p>Turn meaningful conversations about disability and inclusion into practical ideas, partnerships and commitments.</p></article><article class="photo" style="--bg:url('${A.people}')"><div></div><b>02</b><small>THE PEOPLE</small><h3>Put lived experience at the centre.</h3><p>People with disabilities are not an audience at the summit. They are voices, leaders, creators and contributors shaping the conversation.</p></article><article class="aqua"><b>03</b><small>THE EXPERIENCE</small><h3>Think. Connect. Challenge. Act.</h3><p>Keynotes, fireside conversations, inclusive labs and immersive experiences create a journey designed to move people from intent to action.</p></article><article class="photo" style="--bg:url('${A.stage}')"><div></div><b>04</b><small>THE OUTCOME</small><h3>Leave with something to build.</h3><p>New perspectives, new relationships and concrete commitments that continue long after the summit ends.</p></article></div><div class="experience-strip"><span>KEYNOTES</span><span>FIRESIDE CONVERSATIONS</span><span>INCLUSIVE LABS</span><span>IMMERSIVE EXPERIENCES</span><span>RECOGNITION</span></div></section>
<section class="register" id="register"><div class="register-image"></div><div class="register-panel reveal"><small>03 / REGISTER YOUR INTEREST</small><h2>Be part of the<br><em>change.</em></h2><p>Register your interest to receive official summit announcements, participation updates and registration details from Triumphs of Talent.</p><form id="interest"><input required name="name" placeholder="Full name" autocomplete="name"><input required type="email" name="email" placeholder="Work email" autocomplete="email"><input required name="phone" placeholder="Phone number" autocomplete="tel"><button class="btn primary" type="submit">Register your interest <span>↗</span></button></form><span id="status">Your details will take you to the official registration form.</span></div></section>
</main><footer><div><img src="${TOT_LOGO}" alt="Triumphs of Talent"><span>presents</span><b>India Inclusive Summit</b></div><span>© ${new Date().getFullYear()} Triumphs of Talent</span></footer>`;

const loader=document.querySelector('#loader');
const closeLoader=()=>{if(!loader)return;loader.classList.add('loaded');setTimeout(()=>loader.remove(),900)};
setTimeout(closeLoader,2200);
const nav=document.querySelector('nav');
document.querySelector('.menu').onclick=()=>nav.classList.toggle('open');
nav.querySelectorAll('a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));
document.querySelector('#interest').onsubmit=e=>{e.preventDefault();document.querySelector('#status').textContent='Opening official registration…';window.open('https://docs.google.com/forms/d/e/1FAIpQLSfWJzjauPd7oB-5D2od1ztnIsNEOAvrjZ11KawpM_9_WaOQRQ/viewform','_blank','noopener')};
function revealFallback(){const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');o.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>o.observe(x))}revealFallback();
async function motion(){if(matchMedia('(prefers-reduced-motion:reduce)').matches){closeLoader();return}try{await load('https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js');await load('https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js');await load('https://cdn.jsdelivr.net/npm/@studio-freight/lenis@1.0.42/bundled/lenis.min.js')}catch(e){closeLoader();return}gsap.registerPlugin(ScrollTrigger);const l=window.Lenis?new Lenis({duration:1.1,smoothWheel:true}):null;if(l){l.on('scroll',ScrollTrigger.update);gsap.ticker.add(t=>l.raf(t*1000))}gsap.to(loader,{yPercent:-100,duration:1.1,delay:.55,ease:'power4.inOut',onComplete:closeLoader});gsap.from('.home-copy>*',{y:70,opacity:0,stagger:.1,duration:.9,delay:.75,ease:'power4.out'});gsap.to('.home img',{scale:1.15,yPercent:8,ease:'none',scrollTrigger:{trigger:'.home',start:'top top',end:'bottom top',scrub:true}});gsap.from('.why-intro',{y:80,opacity:0,scrollTrigger:{trigger:'.why-intro',start:'top 80%',once:true}});const track=document.querySelector('.why-track');if(innerWidth>760){gsap.to(track,{x:()=>-(track.scrollWidth-innerWidth),ease:'none',scrollTrigger:{trigger:'.why-track',pin:true,scrub:1,start:'top top',end:()=>'+='+(track.scrollWidth-innerWidth),invalidateOnRefresh:true}})}gsap.utils.toArray('.why-track article').forEach(x=>gsap.from(x,{scale:.94,opacity:.55,duration:.8,scrollTrigger:{trigger:x,start:'left 80%'}}));gsap.from('.experience-strip span',{y:30,opacity:0,stagger:.08,scrollTrigger:{trigger:'.experience-strip',start:'top 85%',once:true}});gsap.from('.register-panel',{y:80,opacity:0,scale:.96,scrollTrigger:{trigger:'.register-panel',start:'top 80%',once:true}});addEventListener('pointermove',e=>gsap.to('.cursor',{x:e.clientX,y:e.clientY,duration:.3}));const updateProgress=()=>{const max=document.documentElement.scrollHeight-innerHeight;document.querySelector('.progress').style.width=max>0?(scrollY/max*100)+'%':'0%'};addEventListener('scroll',updateProgress,{passive:true});updateProgress();gsap.utils.toArray('.btn').forEach(b=>{b.addEventListener('pointermove',e=>{const r=b.getBoundingClientRect();gsap.to(b,{x:(e.clientX-r.left-r.width/2)*.08,y:(e.clientY-r.top-r.height/2)*.08,duration:.2})});b.addEventListener('pointerleave',()=>gsap.to(b,{x:0,y:0,duration:.4,ease:'elastic.out(1,.4)'}))});setTimeout(()=>ScrollTrigger.refresh(),100)}motion();